#!/bin/bash

exec > /tmp/jupyter.log 2>&1

export PS4='+ (\t) ${LINENO}: '
#set -x

echo "Args: $@"

export PYENV_ROOT=$HOME/.pyenv
PATH="$PATH:/usr/local/bin"
if command -v pyenv > /dev/null 2>&1; then
    PATH="$PATH:$PYENV_ROOT/shims:$HOME/bin"
    echo "Cwd: $(/bin/pwd)"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    JUPYTER_PREFIX="$(pyenv prefix jupyter)"
    JUPYTER_LIB="$(ls -d $JUPYTER_PREFIX/lib/python*)"
    JUPYTERPATH="$JUPYTER_LIB/site-packages:$JUPYTER_LIB/lib-dynload"

    if [ -f .python-version ]; then
        export PYTHONPATH="$(pypath):$JUPYTERPATH"
    else
        echo "pyenv doesn't appear to be established for this directory"
        exit 1
    fi
    echo "pyenv: $(pyenv local)"
    JP="$JUPYTER_PREFIX/bin/jupyter"
    #nohup $JP lab --no-browser --port=8888 --port-retries=0 --ServerApp.password_required=False >/dev/null 2>&1 &
    nohup $JP lab --port=8888 --port-retries=0 --ServerApp.password_required=False &
else
    echo "pyenv doesn't appear to exist in $PATH"
    exit 1
fi
